### ISSUE TITLE
Sogndal-kampen (og bare den) gir feil ved nedlastning

### ISSUE THREAD

**Issue by havremunken** [RosenborgSupporterSoftware/staut#21]
Exception i STAut-vinduet:

```
java.nio.file.NoSuchFileException: .\archive\2016_LEAGUE_10_Sogndal_476971\47697
1_Sogndal_2016-08-14T11-55.xml
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
        at java.nio.file.Files.newByteChannel(Unknown Source)
        at java.nio.file.Files.createFile(Unknown Source)
        at staut.Collector.download(Collector.java:192)
        at staut.CollectAvailabilityTask.downloadAvailability(CollectAvailabilit
yTask.java:103)
        at staut.CollectAvailabilityTask.run(CollectAvailabilityTask.java:74)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

Siste fil ble hentet ned 23:55 i går. Jeg ser derfor ikke bort fra at det kan være en viktig opplysning at alle nedlastninger som dermed har feilet, har vært på dagens dato, i.e. samme dato som kampdato. Om det har noe å si er jeg derimot helt clueless om.

**Comment by vemundo** [comment]
Hei, på trening men skal se på det når jeg kommer hjem.
1. aug. 2016 12:05 skrev "Rune Jacobsen" notifications@github.com:

**Comment by vemundo** [comment]
Hei,

Feilein tyder på at det ikke har noe med selva nedlastingen å gjøre, men at den ikke klarer å opprette en fil som heter:

.\archive\2016_LEAGUE_10_Sogndal_476971\476971_Sogndal_2016-08-14T11-25.xml

Klarer du opprette en fil med det navnet "manuelt"?

**Comment by vemundo** [comment]
Hmm mistenker at problemet er at katalogen .\archive\2016_LEAGUE_10_Sogndal_476971\ ikke finnes. Kan du sjekke det? Evt prøve å opprette den og se om det hjelper.

**Comment by havremunken** [comment]
Heisann!

Som skrevet på RBKweb - dette fikset problemet. Det jeg er litt skeptisk til er hvordan dette har skjedd - jeg var ikke inne på serveren i går kveld, og ingen andre skal ha tilgang. Hvorfor ble akkurat DEN mappa slettet, og av hva?

Mistenker at dette mysteriet går ned i historien, vel glemt, som en sånn poltergeist som forhåpentligvis ikke dukker opp så ofte. Kan virkelig ikke huske at det har skjedd før.

Men men, fikset, lukket og god kamp!

**Comment by vemundo** [comment]
Du fant ikke noen annen katalog for Sogndal kampen?

Har sett litt i koden etter mulige forklaringer, men har ingen gode ideer så langt. Har du log/output fra collectoren rett før/etter det begynte å feile?

**Comment by havremunken** [comment]
Dessverre, negativt på begge. 

Jeg skal endelig få laget litt logging på Ingest-programmet, som er det eneste som rører filene som kommer, og forhåpentligvis finne ut hva som skjer der. Ingen grunn til å tro at ditt program har gjort noe feil. :)
