### ISSUE TITLE
Norske tegn i motstandernavn ser ut til å lage krøll for collector?

### ISSUE THREAD

**Issue by havremunken** [RosenborgSupporterSoftware/staut#24]
Tagger @vemundo her, tradisjonen tro. :)

Får følgende når collectoren står og prøver å hente fra kampene som ble lagt ut i dag (eksempel, kan kopiere mer logg ved behov):

```
INFO: Downloading into: .\archive\2017_LEAGUE_7_Str\u00f8msgodset_515845\515845_
Str\u00f8msgodset_2017-04-10T12-13.xml  at sun.nio.fs.WindowsException.translate
ToIOException(Unknown Source)

        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
        at java.nio.file.Files.newByteChannel(Unknown Source)
        at java.nio.file.Files.createFile(Unknown Source)
        at staut.Collector.download(Collector.java:280)
        at staut.CollectAvailabilityTask.downloadAvailability(CollectAvailabilit
yTask.java:103)
        at staut.CollectAvailabilityTask.run(CollectAvailabilityTask.java:74)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
INFO: Downloading into: .\archive\2017_LEAGUE_8_Sogndal_515847\515847_Sogndal_20
17-04-10T12-13.xml
java.nio.file.NoSuchFileException: .\archive\2017_LEAGUE_5_Troms\u00f8_515841\51
5841_Troms\u00f8_2017-04-10T12-13.xml
        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
        at java.nio.file.Files.newByteChannel(Unknown Source)
        at java.nio.file.Files.createFile(Unknown Source)
        at staut.Collector.download(Collector.java:280)
        at staut.CollectAvailabilityTask.downloadAvailability(CollectAvailabilit
yTask.java:103)
        at staut.CollectAvailabilityTask.run(CollectAvailabilityTask.java:74)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
INFO: Downloading into: .\archive\2017_LEAGUE_9_Sandefjord_515849\515849_Sandefj
ord_2017-04-10T12-13.xmljava.nio.file.NoSuchFileException: .\archive\2017_LEAGUE
_7_Str\u00f8msgodset_515845\515845_Str\u00f8msgodset_2017-04-10T12-13.xml

        at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
        at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
        at java.nio.file.Files.newByteChannel(Unknown Source)
        at java.nio.file.Files.createFile(Unknown Source)
        at staut.Collector.download(Collector.java:280)
        at staut.CollectAvailabilityTask.downloadAvailability(CollectAvailabilit
yTask.java:103)
        at staut.CollectAvailabilityTask.run(CollectAvailabilityTask.java:74)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
INFO: Finished downloading: .\archive\2017_LEAGUE_4_Brann_515839\515839_Brann_20
17-04-10T12-13.xml (66441 bytes)
```

Det passer jo godt med at vi vel har fått både Tromsø, Strømsgodset og Lillestrøm lagt ut tidligere i dag. :)

**Comment by havremunken** [comment]
Til info så blir de norske tegnene til encodede verdier som inneholder en backslash, noe som lager baluba for programmet som genererer grafer o.l. Skal få gjort det mer robust, men tipper vi nok må fikse dette også. :)

`E:\staut\java\archive\2017_LEAGUE_6_Lillestr\u00f8m_515843`

Istedenfor et directory som heter 2017_LEAGUE_6_Lillestrøm_515843 lager den altså en mappe som heter 2017_LEAGUE_6_Lillestr og inne i den havner en mappe som heter u00f8m_515843. Dette klarer ikke systemet å finne ut av. ;)

**Comment by vemundo** [comment]
\u0058 er Unicode kode for ø:
http://www.fileformat.info/info/unicode/char/00F8/index.htm

Dette er nok et resultat av at shellet du bruker ikke støtter Unicode. Så kan muligens fikses ved å bruke et annet Shell, eller mulig det er andre måter å fikse det på i Windows. Kan sikkert Googles.
