### ISSUE TITLE
Ny sesong, nye URL-issues hos TM?

### ISSUE THREAD

**Issue by havremunken** [RosenborgSupporterSoftware/staut#25]
Tagger @vemundo her per tradisjon.

C:\Users\Administrator\Desktop>e:

E:\>cd \staut\java\

E:\staut\java>"C:\Program Files\Java\jre1.8.0_161\bin\java.exe" -jar .\dist\lib\
STAut.jar --collector
INFO: System file encoding: Cp1252
INFO: Loading configuration from E:\staut\java\dist\lib\configuration.properties

INFO: Could not open URL http://www.ticketmaster.no/venue/lerkendal-stadion-tron
dheim-billetter/TLD/25?attractions=100563, status 301
INFO: Redirecting to https://www.ticketmaster.no/venue/lerkendal-stadion-trondhe
im-billetter/TLD/25?attractions=100563
INFO: Updating event collections.

..and nothing continues to happen.

Kunne du ha kjørt en runde lokalt og sett om du kan se hvorfor det ikke kommer noen data?

Takker!

**Comment by vemundo** [comment]
Skal se på det i morgen. :)

Den tor. 15. feb. 2018, 21:21 skrev Rune Jacobsen <notifications@github.com

**Comment by havremunken** [comment]
Konge :)

Men når jeg tenker meg om... så er det vel kun sesongkort, treningskamper og mesterfinale som er ute til generelt salg ennå. Ingen seriekamper på Lerkendal. Så.. det er godt mulig det er hele forklaringen. :)

**Comment by havremunken** [comment]
@vemundo Da skal vi være igang med salget, og vi får en feil:

```
Round: 0
Code: null
AvailabilityURL: http://www.ticketmaster.no/ism/availability/555493
GeometryURL: http://www.ticketmaster.no/ism/geometry/555493
EventURL: https://www.ticketmaster.no/event/555493
INFO: Starting collection of URL: http://www.ticketmaster.no/ism/availability/55
5493 every 10 minutes.
java.lang.NullPointerException
        at staut.EventInfo.isLeagueGame(EventInfo.java:252)
        at staut.EventInfo.getOpponent(EventInfo.java:66)
        at staut.EventInfo.getOpponentWithoutSlash(EventInfo.java:85)
        at staut.CollectAvailabilityTask.getArchiveDirectory(CollectAvailability
Task.java:25)
        at staut.CollectAvailabilityTask.writeEventInfo(CollectAvailabilityTask.
java:35)
        at staut.CheckEventsTask.startAvailabilityCollection(CheckEventsTask.jav
a:59)
        at staut.CheckEventsTask.updateEventCollects(CheckEventsTask.java:45)
        at staut.CheckEventsTask.run(CheckEventsTask.java:18)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown 

```

**Comment by vemundo** [comment]
Skal sjekke hva som er endret.

Den man. 26. feb. 2018, 14:22 skrev Rune Jacobsen <notifications@github.com

**Comment by vemundo** [comment]
Har pushet en fiks, så burde det virke frem til første cupkamp :)

**Comment by havremunken** [comment]
Funka det, takk! Da venter vi med spenning på hjemmekamp i NM og ser hva som skjer!
