### ISSUE TITLE
Kvalik-kamp mot Valur lager krøll igjen

### ISSUE THREAD

**Issue by havremunken** [RosenborgSupporterSoftware/staut#26]
Får følgende exception når den forsøker å hente data for eventen:

```
INFO: Redirecting to https://www.ticketmaster.no/venue/lerkendal-stadion-trondhe
im-billetter/TLD/25?attractions=100563
INFO: Could not open URL http://www.ticketmaster.no/event/555521, status 301
INFO: Redirecting to https://www.ticketmaster.no/event/555521
INFO: Extracting event information from URL: https://www.ticketmaster.no/event/5
55521
INFO: Could not open URL http://www.ticketmaster.no/event/579817, status 301
INFO: Redirecting to https://www.ticketmaster.no/event/579817
INFO: Extracting event information from URL: https://www.ticketmaster.no/event/5
79817
java.lang.NumberFormatException: For input string: "Q1"
        at java.lang.NumberFormatException.forInputString(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at java.lang.Integer.parseInt(Unknown Source)
        at staut.Collector.extractEventInfo(Collector.java:174)
        at staut.Collector.findActiveEvents(Collector.java:75)
        at staut.CheckEventsTask.updateEventCollects(CheckEventsTask.java:25)
        at staut.CheckEventsTask.run(CheckEventsTask.java:18)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

Litt tidlig å si om collection av andre kamper går som det skal så lenge. En restart av STAut har så langt ikke vist at den fortsetter å hente data for andre kamper.

Obligatorisk tag: @vemundo :)

**Comment by vemundo** [comment]
Skal på sett på det, så snart jeg får til. Er på vei på ferie med ny laptop så må få lastet ned og satt opp miljøet.

**Comment by vemundo** [comment]
Har fått pusha en fiks.

**Comment by havremunken** [comment]
Tipp topp, tommel opp - ser ut til å ha løst det, takk. :)
