### ISSUE TITLE
Issue med collecting på Celtic

### ISSUE THREAD

**Issue by havremunken** [RosenborgSupporterSoftware/staut#27]
Får følgende exception når den forsøker å fange opp hjemmekampen mot Celtic:

```
INFO: Updating event collections.
INFO: New event:
ID: 582029
Name: Rosenborg - Celtic (2. kvalik Champions League)
Date: 01.08.2018
Time: 20:45
Location: null
Competition: null
Round: 0
Code: null
AvailabilityURL: http://www.ticketmaster.no/ism/availability/582029
GeometryURL: http://www.ticketmaster.no/ism/geometry/582029
EventURL: https://www.ticketmaster.no/event/582029
INFO: Starting collection of URL: http://www.ticketmaster.no/ism/availability/58
2029 every 10 minutes.
java.lang.NullPointerException
        at staut.EventInfo.isLeagueGame(EventInfo.java:253)
        at staut.EventInfo.getOpponent(EventInfo.java:67)
        at staut.EventInfo.getOpponentWithoutSlash(EventInfo.java:86)
        at staut.CollectAvailabilityTask.getArchiveDirectory(CollectAvailability
Task.java:25)
        at staut.CollectAvailabilityTask.writeEventInfo(CollectAvailabilityTask.
java:35)
        at staut.CheckEventsTask.startAvailabilityCollection(CheckEventsTask.jav
a:59)
        at staut.CheckEventsTask.updateEventCollects(CheckEventsTask.java:45)
        at staut.CheckEventsTask.run(CheckEventsTask.java:18)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.
run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

```

@vemundo tag for obvious reasons. :)

**Comment by vemundo** [comment]
Har pushet en slags fiks nå.

**Comment by havremunken** [comment]
Funka den!
