### ISSUE TITLE
Problemer med å kjøre java-collector på Windows 2008 server

### ISSUE THREAD

**Issue by havremunken** [RosenborgSupporterSoftware/staut#3]
Siden jeg begynner å nærme meg med databasekoden (har den i en lokal branch her hos meg foreløpig, skal pushe så fort jeg ikke skammer meg så mye over koden lengre) tenkte jeg å sette igang en collector på server-boksen hjemme hos meg. Dette er noe forholdsvis gammelt rakleverk av noe hardware, men den funker stort sett til det lille den gjør. Jeg brukte Chocolatey til å laste ned git, jdk8 og ant, og fikk klonet repo og "ant'et" til dist som Vemundo beskrev på RBKweb. 

Når jeg kjører får jeg dog en exception:

```
PS E:\staut\java> & 'C:\Program Files\Java\jre1.8.0_45\bin\java.exe' -jar .\dist\lib\STAut.jar --collector
Loading configuration from E:\staut\java\dist\lib\configuration.properties
java.lang.ArrayIndexOutOfBoundsException: 5
        at staut.Collector.findActiveEvents(Collector.java:72)
        at staut.CheckEventsTask.updateEventCollects(CheckEventsTask.java:25)
        at staut.CheckEventsTask.run(CheckEventsTask.java:18)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

Kanskje verdt å påpeke at jeg ikke har gjort noen endringer i configuration.properties - dette er kjørt direkte etter cloning av repo.

Jeg er helt verdiløs jomfru på java - er dette noe åpenbart feil med miljø eller maskin?

**Comment by vemundo** [comment]
Nei ser ut som du hadde gjort ting riktig, jeg fikk samme feil her. Grunnen var at når jeg parser event ID for hver enkelt kamp fra html siden for Lerkendal hadde en av kampene et uvanlig format (dvs en tag som er der for alle andre kamper manglet). Det gjorde at parsingen knakk, det er ikke veldig intelligente greier. Kan alltids dra inn et stort bibiliotek for å parse html, men lar det være low-tech intill videre. Det er jo bare tekst. Hvis det viser seg at formatet er veldig ustabilt får det evt. revurderes, men tror dette var bare uflaks pga Molde kampen er utsolgt.

Jeg har pushet en fiks så regner med det skal kjøre hos deg også nå.

**Comment by havremunken** [comment]
Det stemte bra - en git pull og ant dist senere kjører den her. :grinning: 

Enig i at det er greit med minst mulig stress rundt denne parsingen foreløpig. Det virker så lenge det virker, og om det blir slutt på det får vi bare revurdere.

**Comment by vemundo** [comment]
Jepp, det er jo litt nybrottsarbeid hele greia. Når noe knekker lærer vi
noe nytt, vi har ikke mulighet til å få full info om hvordan billettservice
jobber.

Vemund

2015-06-27 0:43 GMT+02:00 Rune Jacobsen notifications@github.com:
